-- DROP TABLE users;
CREATE TABLE IF NOT EXISTS users (id INTEGER, wca_id TEXT NOT NULL, email TEXT NOT NULL, password TEXT NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX IF NOT EXISTS wca_id ON users (wca_id);
CREATE UNIQUE INDEX IF NOT EXISTS email ON users (email);